config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  post '/guests/guest_sign_in', to: 'public/guests#new_guest'
  get '/about' => 'public/homes#about', as: 'about'

  namespace :public do
    resources :users, only: [:show, :edit, :update]
    resources :films, only: [:new, :create, :index, :show, :destroy, :edit, :update]

  end

  namespace :admin do
    resources :users, only: [:index, :show]
    resources :films, only: [:show, :destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
  validates :user_id, {presence: true}

  belongs_to :user, optional: true

  def user
    return Film.where(id: self.id)
  end


end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :films

  def self.guest
      find_or_create_by(email: 'guesr@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      end
  end

  def films
    return Film.where(user_id: self.id)
  end
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/films_controller.rb
class Admin::FilmsController < ApplicationController

  def show
    @film = Film.find(params[:id])
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
    redirect_to admin_user_path(current_user.id)
  end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

   config.time_zone = 'Asia/Tokyo'
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
    devise_parameter_sanitizer.permit(:log_in, keys: [:user_name])
  end

  def
    after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
  end

end

app/helpers/admin/films_helper.rb
module Admin::FilmsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/films/show.html.erb
<div class="container m-3">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <h3 class="pb-3 mb-4 font-italic border-bottom"><%= @film.introduction %></h3>
      <div>
        <h2><%= @film.film_title %></h2>
        <p><%= @film.created_at.strftime("%Y-%m-%d %H:%M:%S") %></p>
      </div>
      <div>
        <p><%= @film.body %></p>
      </div>
      <div>
        <div id="star-rate<%= @film.id %>">Excellent!!!</div>
        <script>
          $('#star-rate<%= @film.id%>').raty({
            size      : 36,
            starOff   : '<%= asset_path('star-off.png') %>',
            starOn    : '<%= asset_path('star-on.png') %>',
            half      : false,
            readOnly: true,
            score: <%= @film.evaluation %>,
          });
        </script>
      </div>
      <div>
        <%= link_to "消去する", admin_film_path(@film), method: :delete, class:"text-secondary font-weight-bold" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/admin/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row m-3">
   <div class="col-8 m-3">
    <% @users. each do |user| %>
     <article class="post-preview">
       <h2 class="post-taitle">
        <%= link_to user.user_name, admin_user_path(user.id), class:'text-dark' %>
       </h2>
       <h4 class="post-introduction text-dark">
        <%= user.introduction %>
       </h4>
     <hr>
     </article>
    <% end %>
   </div>
 </div>
</div>

app/views/admin/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row m-3">
  <div class="col-3 md-3">
    <h2>User Info</h2>
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
              <th><%= @user.user_name %></th>
            </tr>
          　<tr>
              <th >introdaction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </thead>
        </table>
  </div>
  <div class="col-8 m-3">
   <% @user.films. each do |film| %>
   <article class="post-preview">
          <h2 class="post-taitle">
            <%= link_to film.introduction, admin_film_path(film.id), class:'text-dark' %>
          </h2>
          <h4 class="post-introduction"><%= link_to film.film_title, admin_film_path(film.id), class:'text-dark' %></h4>
          <div id="star-rate<%= film.id %>">Excellent!!!</div>
          <script>
            $('#star-rate<%= film.id%>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: <%= film.evaluation %>,
            });
          </script>
          <%= link_to "read more", admin_film_path(film.id), class:'text-secondary' %>
          <hr>
     </article>
    <% end %>
  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CinemaReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-danger">
        <div class="container">
          <a class="navbar-brand text-light font-weight-bold" href="/"><i class="fas fa-film"></i> DocuFilm</a>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to 'マイページ', public_user_path(current_user.id), class: 'nav-link text-light' %>
              </li>
              <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to "ユーザー一覧", admin_users_path, class: 'nav-link text-light' %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to "初めての方", about_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-light' %>
              </li>
              <li class="nav-item">
              <%= link_to "ゲストログイン（閲覧用）", guests_guest_sign_in_path, method: :post, class: 'nav-link text-light' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

     <footer>
      <div class="container mt-5">
        <div class="row">
         <div class="mx-auto">
           <p>Copyright © DocuFilm All Rights Reserved.</p>
         </div>
        </div>
      </div>
     </footer>
  </body>
</html>